set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN R4 [get_ports clk]
set_property PACKAGE_PIN U2 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports {btn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btn[0]}]
set_property PACKAGE_PIN T1 [get_ports {btn[0]}]
set_property PACKAGE_PIN U1 [get_ports {btn[1]}]
set_property PACKAGE_PIN W2 [get_ports {btn[2]}]
set_property PACKAGE_PIN T3 [get_ports {btn[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property PACKAGE_PIN U5 [get_ports uart_rxd]
